## 00 Google Colab intro
Jupyter notebook에서는 그냥 진행하면 된다 <br>
Colab에서는 google drive에 data를 업로드 한 후, 마운트(mount)를 해줘야 사용가능

In [0]:
# Google Drive Mount
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
# Change Directory to Google Drive
cd gdrive/My Drive/

SyntaxError: ignored

### + 단축키 & tip
+ Ctrl + M + A : 바로 위에 새로운 Cell 생성
+ Ctrl + M + B : 바로 밑에 새로운 Cell 생성
+ Ctrl + M + D : 해당 셀을 삭제합니다.
+ Ctrl + M + Z : 삭제한 셀을 다시 생성
+ Ctrl + M + Y : 셀을 Python Code 셀로 지정
+ Ctrl + M + M : 셀을 글 작성을 위한 Markdown 셀로 지정
+ Shift + Enter : 해당 셀 실행
+ tab : 변수이름 자동완성 & parameter 값 보기

### + 입출력 기본
1. a = input( ) _ 이 때, 입력값은 문자열 취급
2. print("A" "B") = print("A"+"B")
3. 문자열 띄어쓰기 : comma(,) 이용
4. end= ' ' : 다음 줄로 넘기지 않고 그 줄 계속 출력

### + GPU와 CPU의 차이
+ CPU : 직렬처리로 최적화된 몇 개의 코어로 구성 <br>
+ GPU : 병렬처리에 사용되며 수 천개의 코어로 구성 - 딥러닝 학습 및 활용 속도에 매우매우 큰 영향

### + 참고사이트 목록
+ [codecademy](https://www.codecademy.com/learn/learn-python) : 직접 코드를 실행시켜가면서 배우는 온라인 파이썬 강의
+ [DataCamp](https://campus.datacamp.com/courses/intro-to-python-for-data-science/) : 데이터 분석을 위한 파이썬을 압축적으로 들을 수 있는 강의
+ [Programmers - Python 입문](https://programmers.co.kr/learn/courses/2) : 온라인 강의를 듣고 관련된 코드를 바로 연습해볼 수 있는 사이트
+ https://gist.github.com/ihoneymon/652be052a0727ad59601 : 마크다운 사용법

## 01 Python Basics

### A. 숫자형
1. integer : 정수 <br>
    Ep_ int()로 사용 <br>
2. float : 실수 <br>
    Ep_ float()으로 사용 <br>
3. complex : 복소수 <br>
    Ex_ 1 + 4j 
4. 8진수 & 16진수 <br>
    Ex_ 0o177 & 0x2A 등 (숫자0 + 각각 알파벳 o or x 사용)<br>    
    <b>operators:</b> +, -, *, /, %, **, // (+=, /= 처럼 사용가능)

In [0]:
# A.3. complex
a = 2 + 3j
print(a.real)                  #실수부분 리턴
print(a.imag)                #허수부분 리턴
print(a.conjugate())      #켤레복소수 리턴
abs(a)                          #절댓값 리턴

2.0
3.0
(2-3j)


3.605551275463989

In [0]:
# 숫자형 operators example (+= 등 처럼 사용하는 경우)
b = 5
b /= 2
b

2.5

#### + math 모듈
+ ceil(x) : 올림 <br>
+ factorial(x) : x! <br>
+ floor(x) : 내림 <br>
+ exp(x) : e**x <br>
+ log(x,base) : log(base)(x) <br>
+ log10(x) : 상용로그 <br>
+ sqrt(x) : root(x) 값 <br>
+ cos(x), sin(x), tan(x) <br>
+ pi, e <br>

In [0]:
import math
math.pi

3.141592653589793

### B. Boolean
1. True / False <br>
<b>operators:</b> ==, !=, >, < >=, <=, is, is not, in, not in, and, or, not <br>
2. while, if, for 등 함수에서 응용

### C. 문자열 자료형
1. string
2. list
3. tuple
4. dictionary
5. set

#### C-1 string
immutable object이므로 수정한 내용이 original string에 업데이트되지 않음 <br>
1. str() : string으로 변환
2. indexing : x[0] <br>
3. slicing : [a:b:c] a부터 b바로 전까지 c간격으로 <br>
Ex_ x[:], x[::-1], x[5:1:-2] <br>
Ep_ silcing활용 => print(text[-5:] + "a" + text[:-1])
4. operators : +, -, in, not in
5. % : 나머지 반환
6. // : 몫 반환
7. """ """ : 줄바꿈할 때 쓰임

##### + string method
+ len(x) : x의 길이 <br>
+ x.find(str) : 해당 str의 index를 반환 (없으면 '-1'을 반환) <br>
+ x.index(str) : 해당 str의 index를 반환 (없으면 오류) <br>
+ x.count(str) : 해당 str의 개수 <br>
+ x.capitalize() : 첫번째 문자를 대문자로 변환 <br>
+ x.lower() : 소문자 만들기 <br>
+ x.upper() : 대문자 만들기 <br>
+ x.lstrip() : 왼쪽 공백 없애기 <br>
+ x.rstrip() : 오른쪽 공백 없애기 <br>
+ x.strip : 양쪽 공백 없애기 <br>
+ x.split(str) : 해당 str을 기준으로 앞과 뒤로 나눔 <br>
+ x.replace(old, new) : old string을 new string으로 바꿔줌 <br>
+ x.startswith(str) : 해당 str으로 시작하면 True, 아니면 False <br>
+ x.endswith(str) : 해당 str으로 끝나면 True, 아니면 False <br>
+ xisalpha : string이 모두 alphabet이면 True, 아니면 False <br>
+ x.isnumeric : string이 모두 number이면 True, 아니면 False <br>
+ x.isalnum : string이 모두 alphabet, number이면 True, 아니면 False <br>
+ " ".join(str) : str 사이사이에 " " 안에 있는 것을 삽입 <br>
+ sorted(str) : str을 알파벳순으로 정렬 (띄어쓰기는 맨앞) <br>

In [0]:
# split 사용법
str1 = "Wanna be happy"
str1.split('a')

['W', 'nn', ' be h', 'ppy']

In [0]:
# join 사용법
str2 = ",".join('will')
str2

'w,i,l,l'

##### + escape code
+ \n : 줄바꿈 <br>
+ \t : 탭간격 <br>
+ \\\ : 문자 \ 표현 <br>
+ \\', \\" : 따옴표 표현

In [0]:
# sep= 이용법
print('Can', 'You', 'Guess?', sep="\n")

Can
You
Guess?


##### + formatting <br>
1) % 사용
+ %s : 문자열 formatting
+ %c : 문자 1개 formatting
+ %d : 정수 formatting
+ %f : 소수 formatting
+ %% : 문자 % 구현 <br>

2) format 함수
+ str.format() : 함수를 이용한 formatting 방법
+ {{  }}.format() : 중괄호 {  } 구현

3) f 문자열
+ f"str" : format 함수와 비슷하게 적용되는 formatting 방법
+ f{{  }} : 중괄호 {  } 구현

4) 정렬 & 공백 (소수점 나타내기)
+ %숫자s : 오른쪽 정렬, 나머지는 숫자만큼 공백
+ %-숫자s : 왼쪽 정렬, 나머지는 숫자만큼 공백
+ %.숫자f : 소수점 표현
+ "{0:>10}".format() : 오른쪽 정렬
+ "{0:<10}".format() : 왼쪽 정렬
+ "{0:^10}".format() : 가운데 정렬
+ "{0:a^10}".format() : 공백을 a로 채움
+ "{0:.숫자f}".format() : 소수점  표현
+ format 함수의 '0' 위치에 str 등을 넣으면 같은 결과


In [0]:
# % 두개 넣는 예시
n = 3
day = 'sunday'
for1 = "I ate %d apples on %s morning" % (n,day)
for1

'I ate 3 apples on sunday morning'

In [0]:
# 문자 % 표시법
for2 = "It is %d%% off now!" % 90
for2

'It is 90% off now!'

In [0]:
# format 함수 예시
for3 = "I need {} more pens right {}." .format(3,'now')
for3

'I need 3 more pens right now.'

In [0]:
# format에서 이름으로 넣기
for4 = 'Do you {a} me?' .format(a='believe')
for4

'Do you believe me?'

In [0]:
# f 문자열 예시
age = 22
for5 = f"OMG, I'll be {age + 1} years old next year."
for5

"OMG, I'll be 23 years old next year."

In [0]:
# 정렬, 공백, 소수점 (%)
blank1 = "Your %10s is %.2f." % ('grade', 95.38492)
blank1

'Your      grade is 95.38.'

In [0]:
# 정렬, 공백, 소수점 (format 함수)
blank2 = "{0:!<10}".format("Isabella")
blank2

'Isabella!!'

In [0]:
 # 정렬, 공백, 소수점 (format 함수) _ :와 .사이에 '0' 넣어도 same result
 x = 90.3423587
 blank3 = "{0:.3f}".format(x)
 blank3

'90.342'

In [0]:
# 정렬, 공백, 소수점 (f 문자열)
blank4 = f'{"^^":*^6}'
blank4

'**^^**'

#### C-2 list
mutable object이므로 수정시 바로 original list에 업데이트 됨
1. list() or [] : list로 변환 (a = list() _ 빈 리스트)
2. indexing & slicing <br>
Ep_string과 동일 <br> 
Ep_Multidimensional lists : x[0][0], x[1][1:3]
3. operators : +, *, in (type 맞춰주기)

In [0]:
# multidimensional lists
a = [1, 2, 3, ['a', 'b', 'c'], 4, 5]
a[3][:2]

['a', 'b']

##### + list method
+ len(x) : list(x)의 길이
+ min(x) : 최소값 반환
+ max(x) : 최댓값 반환
+ del x[ ] : 해당 요소 삭제 ([ ]안에 슬라이싱(:)도 가능)
+ x.append(value) : list 맨끝에 value 추가
+ x.extend(list) : list를 추가
+ x.pop(index) : 해당 index에 있는 value를 돌려주고 삭제 (x.pop() = 맨 마지막 삭제)
+ x.remove(value) : list에서 맨 첫번째에 나오는 value 삭제
+ x.count(value) : value 개수 반환
+ x.insert(index, value) : 해당 index에 value 삽입
+ x.index(value) : value 위치 반환 (lowest number)
+ x.sort() : 순서대로 정렬
+ x.reverse() : 역순 정렬 

In [0]:
# 요소 change
a = [1,2,3,4,5]
a[2] = 0
a

[1, 2, 0, 4, 5]

In [0]:
# extend 예시
a = [1,2,3]
b = [4,5]
c = [6,7]
a.extend(b)
a += c
a

[1, 2, 3, 4, 5, 6, 7]

##### + copying list
그냥 copy해서 수정하면 원본이 아예 바뀌어버림<br>
본래list[:] 해서 copy하면, copy 수정 시 원본이 바뀌지 않음

In [0]:
# list copy하기 (No)
nlist = [1,3,5,7,9]
nlist_copy = nlist
nlist_copy.append(11)
print(nlist)
print(nlist_copy)

[1, 3, 5, 7, 9, 11]
[1, 3, 5, 7, 9, 11]


In [0]:
# list copy하기 (Yes)
nlist = [1,3,5,7,9]
nlist_realcopy = nlist[:]
nlist_realcopy.append(11)
print(nlist)
print(nlist_realcopy)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9, 11]


#### C-3 tuple
immutable object이므로 수정한 내용이 original tuple에 업데이트되지 않음<br>
1. () or tuple()로 나타냄
2. 요소가 하나일 때 맨 끝에 comma(,)를 써주어야 함
3. 괄호를 적지 않아도 comma(,)로 나열하면 tuple로 인식
4. operators = +, *, in
5. tuple은 수정이 불가함 (추가, 삭제 등의 메소드 사용 불가능)
6. indexing, slicing은 가능함


##### + tuple method
+ len(x) : tuple의 길이 반환
+ max(x) : 최대값 반환
+ min(x) : 최솟값 반환
+ x.index(value) : value 위치 반환 (lowest)
+ x.count(value) : value 개수 반환

#### C-4 dictionary
mutable object이므로 수정시 바로 original dict에 업데이트 됨
1. {key:value}의 형태로, {} or dict()로 나타냄
2. key : immutable data type (str, num, tuple 등), 그리고 unique
3. value : any type, unique 안해도 OK
4. indexing, slicing 불가

In [0]:
# two-value sequences를 dict으로 만들기
a = [(1,2),(3,4),(5,6)]
b = [[1,2],[3,4],[5,6]]
print(dict(a), dict(b), sep="\n")

{1: 2, 3: 4, 5: 6}
{1: 2, 3: 4, 5: 6}


##### + dictionary method
+ dict['key'] : 해당 key의 value를 반환
+ dict['key'] = value : 새로 한 쌍이 추가됨 (이미 있는 key면 value만 업뎃)
+ key in / not in dict : 있으면 True, 없으면 False
+ len(dict) : 길이 반환 (한쌍으로)
+ del dict['key'] : 해당 key의 한쌍 삭제
+ dict.clear() : 모두 삭제
+ dict.items() : 모든 쌍을 tuple로 반환
+ dict.keys() : 모든 key들을 list로 반환
+ dict.values() : 모든 value들을 list로 반환
+ dict.update(dict2) : dict2를 dict에 추가 (key 겹칠 시, dict2 value값 사용)
+ dict.get('key', 디폴트) : 해당 key가 없을 시 디폴트 값을 반환

In [0]:
# 새로 추가하기
dict1 = {'a' : 1}
dict1['a'] = 2
dict1['b'] = 3
dict1

{'a': 2, 'b': 3}

In [0]:
# item() 활용
dict2 = {'A' : 'a', 'B' : 'b'}
dict2.items()

dict_items([('A', 'a'), ('B', 'b')])

In [0]:
# get() 활용
dict3 = {"Q" : 1, "W" : 2}
print(dict3.get("Q"), dict3.get("E",'No'), sep='\n')

1
No


##### + copying dictionary
newdict = dict1.copy()를 해서 복사해주어야 원본값이 안바뀜

#### C-5 set
immutable object이므로 수정한 내용이 original set에 업데이트되지 않음
1. { } or set() 으로 표현 (빈 set은 후자만 사용)
2. unique 하고(=중복이 없고), 순서도 없음 : 필터 역할
3. set({dict})인 경우, key를 set으로 반환
4. indexing, slicing 불가능
5. in, not in, ==, !=, <=, >= : True or False 반환

##### + set method
+ a & b : 교집합
+ a | b : 합집합
+ a.union(b) : 합집합
+ a - b : 차집합
+ a.difference(b) : 차집합
+ a ^ b : 대칭차집합
+ len() : 길이 반환
+ x.add(element) : 값 1개 추가
+ x.update([element]) : 여러 값 추가
+ x.discard(element) : 특정값 제거
+ x.remove(element) : 특정값 제거 (이미 없으면 error)
+ x.clear() : 모든 element 제거

##### + copying set
newset = set1.copy()를 해서 복사해주어야 원본값이 안바뀜

## 02 제어문 (if, while, for)

### A. if문
1. 비교연산자 : <, >, ==, !=, <=, >=
2. 기타연산자 : or, and, not, in, not in
3. pass : 아무일이 일어나지 않도록 설정 (들여씀)
4. elif : else + if
5. 조건문 뒤에 ' : ' 붙이기
6. 한줄 출력 가능


In [0]:
# 한줄로 묘사하는 법 & pass 사용
lista = ['A', 'B', 'C']
if 'C' in lista: pass
else: print('None')

### B. while문
1. 조건문이 참인 동안 반복, 거짓이면  빠져나옴
2. 조건문 뒤에 ' : ' 붙이기
3. break = while문 강제로 빠져나가기 (들여씀)
4. continue = while문 맨 처음(조건문)으로 돌아가기
5. while True = 조건문이 항상 참이므로 무한 루프 : 빠져나오려면 [ctrl + C]
6. 한줄 출력 가능

In [0]:
# 1-10까지의 합_ 마지막 sum만 나타내고 싶으면 print는 밖으로 빼주기
sum = 0
i = 1
while i <= 10:
  sum += i
  i += 1
print("Sum is", sum)

Sum is 55


In [0]:
# 1-10 중 홀수만 출력하기
a = 0
while a <10:
  a += 1
  if a % 2 == 0: continue
  print(a)

1
3
5
7
9


### C. for문
1. for 변수 in (리스트, 튜플, 문자열 등)
2. 조건문 뒤에 ' : ' 붙이기
3. continue 사용 가능 (필요한 것만 출력)
4. 리스트 내포 : [표현식 for x in ~ (if 조건문)] _ if 생략가능
5. 한줄 출력 가능

In [0]:
# list comprehension
a = [1,2,3,4]
result = [num * 3 for num in a]
print(result)

[3, 6, 9, 12]


#### + range 함수
1. range(시작 숫자, 끝 숫자, 간격) : 끝 숫자 포함 안됨
2. 위에 list 등 있을 시, range(len()) 으로 사용

In [0]:
# range 함수 _ 구구단
for i in range(2,10):
  for j in range(1,10):
    print(i * j, end=" ")
  print(' ')

2 4 6 8 10 12 14 16 18  
3 6 9 12 15 18 21 24 27  
4 8 12 16 20 24 28 32 36  
5 10 15 20 25 30 35 40 45  
6 12 18 24 30 36 42 48 54  
7 14 21 28 35 42 49 56 63  
8 16 24 32 40 48 56 64 72  
9 18 27 36 45 54 63 72 81  


## 03 함수

### A. def 함수
1. 일반적인 함수
        def 함수이름(매개변수):
              return 결과값

        결과값을 받을 변수 = 함수이름(인수)

2. 입력값이 없는 함수
        def 함수이름():
              return 결과값

        결과값을 받을 변수 = 함수이름()
     
3. 결과값이 없는 함수
        def 함수이름(매개변수):

        함수이름(인수)

        
4. 입력값, 결과값 모두 없는 함수
        def 함수이름():

        함수이름()

+ return값은 오로지 1개
+ return으로 함수를 빠져나갈 수 있음
+ 함수 안에서 선언한 매개변수는 함수 안에서만 효력
+ 함수 밖의 변수를 변경하는 법 : return, global 사용

In [0]:
# 결과값이 없는 함수
def sumf(a,b):
  print(a + b)

a = sumf(3,4)
print(a) # None : 결과값 없음을 의미

7
None


In [0]:
# 매개변수 지정해서 호출 
def divif(a,b):
  return a/b

r = divif(2,4)
l = divif(b=2, a=4) # 변수만 제대로 지정해주면 순서 상관이 없음
print(r,l)

0.5 2.0


In [0]:
# return값은 only 1개
def re(a,b):
  return a+b, a*b

result = re(1,2)
print(result) # return값은 1개이므로 tuple로 결과값을 반환

(3, 2)


#### + 여러개 입력받는 함수
def 함수이름(*매개변수): <br>
모든 입력값들을 tuple로 반환

In [0]:
# 입력값이 여러개
def app(*args):
  return args

a = app(1,2,3,4,5)
print(a)

(1, 2, 3, 4, 5)


#### + 키워드 파라미터
def 함수이름(**매개변수): <br>
모든 입력값들을 dict으로 반환

In [0]:
# 키워드 파라미터
def app2(**args):
  return args

b = app2(apple = 'red')
print(b)

{'apple': 'red'}


In [0]:
# 함수 응용
def intro(name, *major, **info):
  print('Name:', name)
  print("Major:")
  for ma in major:
    print(ma)
  for inf in info:
    print(inf, ":", info[inf])

intro("Isabella", "Economics", "Industrial Engineering", Age = "22", Gender = 'Female')

Name: Isabella
Major:
Economics
Industrial Engineering
Age : 22
Gender : Female


#### + 매개변수에 초깃값 설정하기
+ 입력시 초깃값 설정한 변수는 적지 않아도 됨
+ 초깃값은 맨 마지막에만 설정가능


In [0]:
# 초깃값 예시
def address(country, city, current=True):
  print("Address: %s, %s." %(country, city))
  if current:
    print("living")
  else:
    print("Not living")

a = address('Korea', 'Seoul')
b = address("USA", 'NYC', False)

Address: Korea, Seoul.
living
Address: USA, NYC.
Not living


### B. lambda 함수
1. lambda 매개변수1, 매개변수2 ... (한줄로 표현)
2. return 없이도 결과값 반환

In [0]:
a = lambda q, w: q + w
result = a(5,7)
print(result)

12


## 04 여러 methods

### A. 내장함수
+ abs(x) : 절댓값 반환
+ all(x) : 해당 자료의 True, False를 반환 (Ex_ 0이 있으면 False 등)
+ any(x) : 자료 중 하나라도 참이면 True, 모두 거짓일 때 False
+ chr(x) : 아스키 코드 값을 입력받고, 이에 해당하는 문자 출력 (0-127)
+ dir(x) : 객체(list, dict 등)가 가지고 있는 함수를 보여줌 (클래스 내의 메소드)
+ divmod(x,y) : x/y의 몫과 나머지를 tuple로 반환 (//, %)
+ enumerate(x) : list, tuple, str을 인덱스 값을 포함하여 반환
+ eval(expression) : 표현식을 문자열로 입력받아 실행한 결과값을 반환
+ filter() : 함수식에서 참인 값만 반환
+ hex(x) : 정수 값을 입력받아 16진수로 변환
+ id(x) : 객체를 입력받아 고유 주소 값 반환
+ int(x, radix) : radix 진수로 표현된 x를 10진수로 변환
+ isinstance(object, class) : 해당 object가 class안에 있으면 True, 아니면 False
+ map(f, iterable) : 입력받은 iterable자료형의 각 요소를 f가 수행한 결과를 묶어서 반환
+ max(x) : 최댓값 반환
+ min(x) : 최솟값 반환
+ oct(x) : 정수 값을 입력받아 8진수로 변환
+ ord(x) : 문자의 아스키 코드값을 반환
+ pow(x, y) : x**y 값 반환
+ round(x, digits) : x를 입력받아 소수점 digits까지 반올림 (x만 있으면 just 반올림)
+ sorted(x) : 입력값을 정렬한 후 반환
+ sum(x) : list, tuple 요소의 합 반환
+ type(x) : 자료형이 무엇인지 반환
+ zip(x) : 동일한 개수로 이루어진 자료형을 묶어줌

In [0]:
# enumerate 함수
for i, name in enumerate(['Apple', 'Banana', 'Cherry']):
  print(i, name)

0 Apple
1 Banana
2 Cherry


In [0]:
# eval 함수
eval("'te' + 'a'")

'tea'

In [0]:
# filter 함수
list(filter(lambda x: x>0, [1,-3,2,0,-5,6]))

[1, 2, 6]

In [0]:
# map 함수
list(map(lambda a: a*2, [1,2,3,4]))

[2, 4, 6, 8]

In [0]:
# zip 함수_index별로 묶음
list(zip([1,2,3],[4,5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

#### + 파일 읽고 쓰기
open(파일 이름, 모드) : 파일을 열 때 사용 <br>
+ r : 읽기모드
+ w : 쓰기모드
+ a : 새로운 내용 추가


In [0]:
# txt 파일 불러오기
# open(,,) 첫번째 칸에 자신이 파일을 저장해놓은 위치를 써야 함

f = open("code_bella_data/my_life.txt", 'r', encoding='UTF8')
f.read()

"The life is only once. Why do you make efforts commonly, don't want to live commonly."

In [0]:
# 파일 닫기

f.close()

In [0]:
# txt 파일로 내보내기

f = open("code_bella_data/20200522_theday.txt", 'w', encoding='UTF8')
f.write("The word 'impossible' is not in my dictionary.")
f.close()

### B. 외장함수

#### B-1 time 모듈
import time 을 맨처음 해줘야 함
+ time.time() : 현재 시간을 실수형태(초 단위)로 반환 (세계표준시)
+ time.localtime() : 위 실수 값을 연도, 월, 일, 시, 분, 초 형태로 변환
+ time.asctime() : 위 결과값을 tuple로 반환
+ time.ctime() : time.asctime(time.localtime(time.time()))와 동일
+ time.strftime() : 출력할 형식 포맷 코드 사용해서 나타냄
+ time.sleep() : 일정한 시간 간격을 두고 루프 실행

##### + strftime 함수 코드
너무 많아서 몇개만 정리함
+ %A : 요일
+ %B : 달
+ %c : 날짜, 시간 출력
+ %d : 날
+ %H : 시간(24시간)
+ %I : 시간(12시간)
+ %M : 분
+ %p : AM or PM
+ %S : 초 
+ %x : 현재 설정된 local 날짜 출력
+ %X : 현재 설정된 local 시간 출력
+ %Y : 년
+ %Z : 시간대


In [0]:
# time 예시
import time
a = time.asctime(time.localtime(time.time()))
b = time.ctime()
print(a,b, sep='\n')

Fri May 22 21:02:12 2020
Fri May 22 21:02:12 2020


In [0]:
# strftime 예시
time.strftime('%z', time.localtime(time.time()))

'+0900'

In [0]:
# sleep 예시
for i in range(10):
  print(i, end=' ')
  time.sleep(1) # 1초마다 한 숫자씩 반환

0 1 2 3 4 5 6 7 8 9 

#### B-2 calendar 모듈
import calendar을 처음에 해주기
+ calendar.calendar(연) : 그 해 전체 달력 (=calendar.prcal(연))
+ calendar.prmonth(연, 월) : 해당 연도의 월을 반환
+ calendar.weekday(연, 월, 일) : 해당 날짜의 요일을 숫자(월=0, 일=6)로 반환
+ calendar.monthrange(연, 월) : 해당 월의 1일의 요일과, 몇일인지 tuple로 반환


In [0]:
# monthrange 예시
import calendar
calendar.monthrange(2020,3)

(6, 31)

#### B-3 random 모듈
import random 맨 처음에 해주기
+ random.random() : 0 ~ 1 사이에서 랜덤 실수
+ random.randint(숫자, 숫자) : 숫자 사이의 랜덤 정수

In [0]:
# randint 예시
import random
random.randint(1,10)

6

## 05 Numpy
고성능의 수치 계산용 패키지 <br>
빠르고 효율적인 데이터 배열 처리를 지원함 <br>
다양한 매서드 존재 <br>
pandas, scipy, matplotlib 등 여러 패키지들의 기반이 되는 라이브러리

In [0]:
import numpy as np

### A. array

#### A-1 numpy array 생성 (1,2,3차원)

In [0]:
# 1차원 numpy array 만들기 (2 methods)
# 1) list -> numpy array
list1st = [1, 2, 3]
dim1_arr = np.array(list1st)

# 2) 바로 numpy array 생성 
dim1_arr2 = np.array([1, 2, 3])
dim1_arr3 = np.array(range(1,4))

print(list1st)
print(dim1_arr)
print(dim1_arr2)
print(dim1_arr3)

[1, 2, 3]
[1 2 3]
[1 2 3]
[1 2 3]


In [0]:
# 2차원 numpy array 만들기 
dim2_arr = np.array(
    [[1, 2, 3],
    [4, 5, 6]],)

print(dim2_arr)

[[1 2 3]
 [4 5 6]]


In [0]:
# 3차원 numpy array 만들기
dim3_arr = np.array(
    [[[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]]],)
print(dim3_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##### + ndarray attributes

In [0]:
# ndarray.ndim (차원을 반환)
dim1_arr.ndim

1

In [0]:
# ndarray.shape ((행,렬) 반환)
dim2_arr.shape

(2, 3)

In [0]:
# ndarray.size (array에 있는 모든 elements 반환)
dim3_arr.size

12

In [0]:
# ndarray.dtype (date type을 반환 _ 지정하지 않을 경우 유추해서 생성)
print(dim1_arr.dtype)
dim1_arr_float = np.array([1, 2, 3], dtype=float)
dim1_arr_float.dtype

int32


dtype('float64')

In [0]:
# numpy의 n차원의 배열 객체
type(dim2_arr)

numpy.ndarray

#### A-2 reshape & resize
reshape : array의 차원을 반환, 실제 배열을 바꾸지 않고 only return <br>
resize : reshape과 same 기능, but 배열 자체를 바꿈 <br>
둘다 size가 같아야 변환이 가능함

In [0]:
arr1 = np.array(range(10))
print(arr1)
arr1.shape, arr1.ndim

[0 1 2 3 4 5 6 7 8 9]


((10,), 1)

In [0]:
# reshape (2 methods)
print(arr1.reshape(2, 5))
print(np.reshape(arr1, (2, 5)))
arr1

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# resize
arr1.resize(2, 5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
# reshape에서 -1사용 (resize에서는 사용불가)
# -1을 하나 써주고 나머지 수를 넣으면, -1 자리를 원래 배열의 길이와 남은 차원으로부터 추정
# 숫자의 개수 = 차원
arr_trans1 = arr1.reshape(-1, 2, 5)
print(arr_trans1, arr_trans1.shape)

arr_trans2 = arr1.reshape(2, -1)
print(arr_trans2, arr_trans2.shape)

[[[0 1 2 3 4]
  [5 6 7 8 9]]] (1, 2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


##### + newaxis 이용하기

In [0]:
nx = np.array([1,2,3])
nx1 = nx[np.newaxis, :]
nx2 = nx[:, np.newaxis]
print(nx, nx.shape, nx.ndim)
print(nx1, nx1.shape, nx1.ndim)
print(nx2, nx2.shape, nx2.ndim)

[1 2 3] (3,) 1
[[1 2 3]] (1, 3) 2
[[1]
 [2]
 [3]] (3, 1) 2


#### A-3 index & slice
행렬 데이터를 수정하거나 자를 때, 가져올 때 사용 (0부터 시작)

In [0]:
arr_ex = np.array(
    [[[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]]])
arr_ex, arr_ex.shape, arr_ex.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]), (2, 2, 3), 3)

In [0]:
# indexing
print(arr_ex[1])
print(arr_ex[0][1][2])

[[ 7  8  9]
 [10 11 12]]
6


In [0]:
# slicing
arr_ex_sl = arr_ex[1:, :, 1:]
arr_ex_sl, arr_ex_sl.ndim #차원은 그대로

(array([[[ 8,  9],
         [11, 12]]]), 3)

In [0]:
# modifying (slicing해서 나온 부분 모두를 0으로 바꿔 넣기)
arr_ex[1:, :, 1:] = 0
arr_ex

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  0,  0],
        [10,  0,  0]]])

### B creation function
1. zeros(shape) : 0으로 이루어진 행렬을 만듬
2. ones(shape) : 1로 이루어진 행렬을 만듬
3. eye(n,m,start-point) : n*m의 단위행렬을 만듬
4. identity(n) : n*n의 단위 행렬을 만듬
5. empty(shape) : 더미 데이터로 이루어진 행렬을 만듬
6. full(shape, fill_value) : 해당 shape에 fill_value를 넣음
7. arange(start, end, step) : range와 같은 역할을 수행
8. linspace(start, end, num) : star ~ end 수 사이를 num개로 동일하게 자른 것
9. stack : 행렬을 쌓음
10. concatenate : 행렬을 결합
11. split : 행렬을 자름 

In [0]:
# 1. zeros (주로 행렬 데이터 생성시 사용) (2 methods)
z1 = np.zeros((2, 3, 2), dtype=int)
z2 = np.zeros_like(arr_ex, dtype=int)
print(z1)
z2

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [0]:
# 2. ones (주로 행렬 데이터 생성시 사용) (2 methods)
o1 = np.ones((4, 3), dtype=int)
o2 = np.ones_like(arr_ex, dtype=int)
print(o1)
o2

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [0]:
# 3. eye (n*m 단위행렬을 만들되, 마지막 숫자는 1을 쓰는 첫번째 지점을 의미)
print(np.eye(3,4,2))
np.eye(2,2) # 마지막 숫자 생략가능

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


array([[1., 0.],
       [0., 1.]])

In [0]:
# 4. identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# 5. empty
np.empty((7,3)) # e : 2.68e+154 -> 2.68 * 10 ** 154 이런식으로 계산

array([[1.30767340e-311, 6.27463370e-322, 0.00000000e+000],
       [0.00000000e+000, 1.89146896e-307, 5.30276956e+180],
       [1.57076922e-076, 4.57223006e-071, 3.25903123e-086],
       [3.35810380e-143, 6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 1.71830429e+185],
       [6.12958251e-062, 2.08799065e-076, 1.05204395e-046],
       [4.97156414e-143, 1.50008929e+248, 2.59305228e-306]])

In [0]:
# 6. full
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [0]:
# 7. arange (맨 마지막에 dtype넣어도 OK)
np.arange(5,10,2)

array([5, 7, 9])

In [0]:
# 8. linspace
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
# 9. stack (vstack, hstack, axis)
na1 = np.arange(5)
na2 = np.arange(5, 10)
print(na1, na2, sep='\n')

[0 1 2 3 4]
[5 6 7 8 9]


In [0]:
na_a0 = np.stack((na1, na2)) # axis = 0
na_s = np.vstack((na1, na2)) # 위 2개는 같다
na_a1 = np.stack((na1, na2), axis = 1)
na_h = np.hstack((na1, na2)) # 안으로 넣은 것 (위 2개는 같지 않음)
print(na3, na_s, sep='\n')
print("\n")
print(na_a1)
print("\n")
print(na_h)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


[0 1 2 3 4 5 6 7 8 9]


In [0]:
# 9-1. 2차원 이상일 때의 stack
na21 = np.arange(1, 13).reshape(2, 2, 3)
na22 = np.arange(1, 13).reshape(2, 2, 3)
print(na21, na22, sep='\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [0]:
na23 = np.stack((na21, na22), axis = 0)
na24 = np.stack((na21, na22), axis = 1)
na25 = np.stack((na21, na22), axis = 2)
na26 = np.stack((na21, na22), axis = 3)
print(na23, na23.shape)
print(na24, na24.shape)
print(na25, na25.shape)
print(na26, na26.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]] (2, 2, 2, 3)
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]

  [[ 7  8  9]
   [10 11 12]]]] (2, 2, 2, 3)
[[[[ 1  2  3]
   [ 1  2  3]]

  [[ 4  5  6]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [ 7  8  9]]

  [[10 11 12]
   [10 11 12]]]] (2, 2, 2, 3)
[[[[ 1  1]
   [ 2  2]
   [ 3  3]]

  [[ 4  4]
   [ 5  5]
   [ 6  6]]]


 [[[ 7  7]
   [ 8  8]
   [ 9  9]]

  [[10 10]
   [11 11]
   [12 12]]]] (2, 2, 3, 2)


In [0]:
# 10. concatenate
# 각 axis를 따라 join (row, column의 개수가 맞아야함)
co1 = np.random.randint(10, size=(2,3))
co2 = np.random.randint(10, size=(3,2))
co3 = np.random.randint(10, size=(3,3))
print(co1, co2, co3, sep='\n')

[[8 0 8]
 [7 3 0]]
[[5 5]
 [6 0]
 [2 2]]
[[7 9 2]
 [0 1 0]
 [2 0 3]]


In [0]:
co13 = np.concatenate((co1, co3)) # axis = 0
co23 = np.concatenate((co2, co3), axis = 1)
print(co13, co23, sep='\n')

[[8 0 8]
 [7 3 0]
 [7 9 2]
 [0 1 0]
 [2 0 3]]
[[5 5 7 9 2]
 [6 0 0 1 0]
 [2 2 2 0 3]]


In [0]:
# 11. split (vsplit, hsplit, axis)
s1 = np.arange(16).reshape((4,4))
s1v1, s1v2 = np.vsplit(s1,[2]) # (= np.split(s1,[2]))
s1h1, s1h2 = np.hsplit(s1,[2]) # (= np.split(s1,[2], axis = 1))
print(s1, s1v1, s1v2, s1h1, s1h2, sep = '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [0]:
# 11-1. 다른 표현법들
s2 = np.split(s1, [2])[0] # 2개 중 첫항만 나옴
s3 = np.split(s1, [1,1])[0] # [1,1]처럼 다각도로 split 가능
print(s2, s3, sep='\n')

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]]


### C random function
+ random.seed(seed) : 랜덤 숫자를 만들기 전 처음 시작할 숫자 (알고리즘 시작값)
+ random.rand(shape) : 0~1 사이의 균일 분포에서 추출
+ random.randn(shape) : 가우시안 표준 정규분포에서 추출
+ random.randint(low, high, size) : 최솟값 ~ 최댓값 사이에서 추출

### D probability distribution function
+ random.binomial(n, p, size) : 이항분포 (p<=1)
+ random.chisquare(df, size) : 카이제곱분포
+ random.exponential(scale, size): 지수분포
+ random.f(dfnum, dfden, size) : F분포
+ random.normal(loc, scale, size) : 정규분포 (가우시안)
+ random.poisson(lam, size) : 포아송분포
+ random.standard_t(df, size) : t분포 (자유도 df)
+ random.standard_normal(size) : 표준정규분포 (mean=0, stdev=1)
+ random.uniform(low, high, size) : 균일분포

In [0]:
# 예시 (사이즈를 이렇게 할 수도 있다)
np.random.poisson(5, (3,2))

array([[5, 6],
       [7, 4],
       [5, 4]])

### E operation function
일반적으로 shape이 같아야 가능

#### E-1 general operation
if a = np.array([1,2,3]) and b = np.array([1,3,2])
+ np.add(a,b) : a+b = array([2, 5, 5])
+ np.subtract(a,b) : a-b = array([ 0, -1, 1])
+ np.negative(a) : -a = array([-1, -2, -3])
+ np.multiply(a,b) : a*b = array([1, 6, 6])
+ np.divide(a,b) : a/b = array([1. , 0.66666667, 1.5 ])
+ np.floor_divide(a,b) : a//b = array([1, 0, 1], dtype=int32)
+ np.power(a,b) : a**b = array([1, 8, 9], dtype=int32)
+ np.mod(a,b) : a%b = array([0, 2, 1], dtype=int32)
+ np.equal(a,b) : a==b = array([ True, False, False])
+ np.not_equal(a,b) : a!=b = array([False, True, True])
+ np.less(a,b) : a < b = array([False, True, False])
+ np.less_equal(a,b): a <= b = array([True, True, False])
+ np.greater(a,b) : a > b = array([False, False, True])
+ np.greater_equal(a,b) : a >= b = array([True, False, True])
+ np.bitwise_and(a>=2, b<3) : (a>=2) & (b<3) = array([False, False, True])
+ np.bitwise_or(a>=2, b<3) : (a>=2) | (b<3) = array([True, True, True])

In [0]:
# 내적곱 (Shape이 달라도 가능함)
a = np.arange(1, 11)
b = np.arange(11, 21)
a.dot(b) # (=a@b)

935

##### + Broadcasting
스칼라의 경우 broadcasting으로 연산된다

In [0]:
sa = np.arange(10)
sa + 1 # (= sa + np.ones(10))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
sa * 10
# (= sa + np.full(10,10))

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### E-2 universal function
original array에서 아래연산을 적용한 값이 나옴
+ np.exp : exp값 반환
+ np.log : 자연log값 반환 (ln(x))
+ np.log10 : log10값 (log10(x))
+ np.sqrt : 루트값 반환
+ np.sin, np.cos, np.tan : sin, cos, tan값 반환
+ np.rint : 반올림값 반환
+ np.ceil : 올림값 반환
+ np.floor : 내림값 반환
+ np.abs : 절댓값 반환
+ np.isnan : boolean (숫자면 False)
+ np.isfinite, np.isinf : boolean (각각 유한, 무한)

In [0]:
# Example
e2a = np.array([1,2,3])
np.sqrt(e2a)

array([1.        , 1.41421356, 1.73205081])

#### E-3 aggregation function
axis = 0이면 세로방향, axis = 1이면 가로방향 (세로르 건들고 가로를 건드는 것) <br>
axis가 없으면 전체
+ np.sum(a[,axis]) : 합
+ np.prod(a[,axis]) :곱
+ np.mean(a[,axis]) : 평균
+ np.std(a[,axis]) : 표준편차
+ np.var(a[,axis]) : 분산
+ np.min(a[,axis]) : 최솟값
+ np.max(a[,axis]) : 최댓값
+ np.median(a[,axis]) : 중간값
+ np.percentile(a,q[,axis]) : 해당되는 %의 값
+ np.any(a[,axis]) : 조건에 하나라도 맞으면 true
+ np.all(a[,axis]) : 조건에 모든게 맞아야 true

In [0]:
# Example
e3a = np.arange(1,5).reshape(2,2)
print(e3a)
print(e3a.sum(axis = 0)) # 세로합 (=np.sum(e3a, axis = 0))
print(e3a.sum(axis = 1)) # 가로합 (=np.sum(esa, axis = 1))
np.sum(e3a)

[[1 2]
 [3 4]]
[4 6]
[3 7]


10

In [0]:
# percentile 활용법
np.percentile(e3a, q=[30,70], axis = 0)

array([[1.6, 2.6],
       [2.4, 3.4]])

In [0]:
# any & all
print(np.any(e3a < 2))
print(np.all(e3a < 2))

True
False


#### E-4 sorting and searching function
+ np.sort(a[,axis]) : 오름차순 정렬
+ np.argsort(a[,axis]) : 오름차순 정렬한 것의 index를 반환 (original index) 
+ np.argmax(a[,axis]) : 최댓값의 original index
+ np.argmin(a[,axis]) : 최솟값의 original index
+ np.nonzero(a) : a에 해당하는 것만 반환
+ np.where(condition, x, y) : 조건에 맞게 반환 (아래참고)

In [0]:
# Examples
ssf = np.random.randn(5)
print(ssf)
print(np.sort(ssf))
print(np.argsort(ssf))
print(np.argmax(ssf))
print(np.argmin(ssf))
print(np.nonzero(ssf)) # 그냥 ssf만 쓰면 0이 아닌 것을 반환
print(np.nonzero(ssf < 0)) # 조건을 넣으면 조건 충족시 반환

[-2.04908291 -0.18511647 -0.48364681  0.51739357 -1.72617374]
[-2.04908291 -1.72617374 -0.48364681 -0.18511647  0.51739357]
[0 4 2 1 3]
3
0
(array([0, 1, 2, 3, 4], dtype=int64),)
(array([0, 1, 2, 4], dtype=int64),)


In [0]:
# np.where(조건 충족 index를 반환)
ssf2 = np.random.randint(1,20,5)
print(ssf2)
np.where(ssf2 > 10)

[10 14 18  1 13]


(array([1, 2, 4], dtype=int64),)

In [0]:
# np.where(condition, True값, False값)
np.where(ssf2 > 10, 'O', 'X')

array(['X', 'O', 'O', 'X', 'O'], dtype='<U1')

#### E-5 set logic function
1차원 array에서만 사용가능
+ np.unique(a) : unique한 값을 오름차순으로 정렬
+ np.intersect1d(a, b) : 2개의 array에서 교집합을 오른차순으로 정렬
+ np.union1d(a, b) : 합집합을 오름차순으로 정렬
+ np.in1d(a, b) : b에 해당하는 원소가 a에도 있으면 True, 아니면 False

## 06 Pandas
데이터 분석을 위한 사용이 쉽고 성능이 좋은 오픈소스 python 라이브러리 <br>
크게 두가지의 데이터 타입이 존재 <br>
<br>
01 Series <br>
Index와 Value로 이루어진 데이터 타입 <br>
<br>
02 DataFrame <br>
Index와 Value와 Column으로 이루어진 데이터 타입 <br>
Column은 Series로 이루어져 있다. <br>
엑셀의 테이블 형태로 구성이 되고, Column별로 같은 데이터 타입을 갖는다.

In [0]:
import numpy as np
import pandas as pd

In [0]:
#option 설정 방법
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### A series 

In [0]:
# series 생성
s1 = pd.Series([1,2,3,4,np.nan]) #nan 값은 np.nan로 작성
s2 = pd.Series(np.random.randint(10, size=5)) #랜덤데이터 생성
print(s1, s2, sep='\n')

0    1.0
1    2.0
2    3.0
3    4.0
4   NaN 
dtype: float64
0    8
1    5
2    0
3    8
4    8
dtype: int32


In [0]:
# index 생성
s3 = pd.Series(np.random.randint(10, size=3), index=['A','B','C'])
s4 = pd.Series(np.random.randint(10, size=3), index=['1','2','3'])
print(s3, s4, sep='\n')

A    0
B    9
C    8
dtype: int32
1    6
2    7
3    1
dtype: int32


In [0]:
# index로 value값 확인 (index 생성시)
print(s3.A)
print(s4['1'])

0
6


In [0]:
# dictionary로 series 생성
dic = {"1":1, "2":2, "3":3}
s5 = pd.Series(dic)
s5

1    1
2    2
3    3
dtype: int64

In [0]:
# Series와 index에 이름(name)부여
s3.name = 'random_number'
s3.index.name = 'index_number'
s3

index_number
A    0
B    9
C    8
Name: random_number, dtype: int32

In [0]:
# broadcasting (ndarray와 비슷)
s4 * 10

1    60
2    70
3    10
dtype: int32

In [0]:
# Series 연산 (index없으면 NaN값)
result = s4 + s5
result

1    7
2    9
3    4
dtype: int64

In [0]:
# 특정 index 데이터 확인
print(s4[['1','3']])
print(s4[0::2])
print(s4[::-1]) #거꾸로 나타내기

1    6
3    1
dtype: int32
1    6
3    1
dtype: int32
3    1
2    7
1    6
dtype: int32


In [0]:
# 조건에 맞는 데이터만 필터링 (T,F)
s4[s4 >5]

1    6
2    7
dtype: int32

In [0]:
# for문 사용
for idx, val in s3.items():
    print(idx, val)

A 0
B 9
C 8


In [0]:
# notnull() : NaN 데이터 제거
# isnull() : NaN 데이터 확인
print(s1.isnull())
s1[s1.notnull()]

0    False
1    False
2    False
3    False
4    True 
dtype: bool


0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

### B dataframe

#### B-1 csv파일 읽고 저장


In [0]:
df0 = pd.DataFrame(data = [1,2,3,4], index = range(0,4), columns = ['A'])
df0

A
0  1
1  2
2  3
3  4

In [0]:
# data 불러오기 (csv파일)
df = pd.read_csv("code_bella_data/titanic.csv")
#df
df.head()
#df.tail()

PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S      
1  2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C      
2  3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S      
3  4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S      
4  5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S

In [0]:
# data 원하는 column 불러오기
df2 = pd.read_csv("code_bella_data/titanic.csv", 
                  usecols=["PassengerId","Survived","Age"],
                  nrows=10,
                  index_col='PassengerId')
df2

Survived   Age
PassengerId                
1            0         22.0
2            1         38.0
3            1         26.0
4            1         35.0
5            0         35.0
6            0        NaN  
7            0         54.0
8            0         2.0 
9            1         27.0
10           1         14.0

In [0]:
# index, column, 해당 column의 value 정보 확인하기
df2.index, df2.columns, df2["Age"].values

(Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64', name='PassengerId'),
 Index(['Survived', 'Age'], dtype='object'),
 array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.]))

In [0]:
# column의 type 확인
df2.dtypes

Survived    int64  
Age         float64
dtype: object

In [0]:
# csv로 저장하기 (index=True 이면 index에 해당하는 column이 dataframe에 저장됨)
df2.to_csv("code_bella_data/titanic_index_False.csv", index = False)
df2.to_csv("code_bella_data/titanic_index_True.csv")

In [0]:
dff = pd.read_csv('code_bella_data/titanic_index_False.csv')
dft = pd.read_csv('code_bella_data/titanic_index_True.csv')
dff.head()

Survived   Age
0         0  22.0
1         1  38.0
2         1  26.0
3         1  35.0
4         0  35.0

In [0]:
dft.head()

PassengerId  Survived   Age
0            1         0  22.0
1            2         1  38.0
2            3         1  26.0
3            4         1  35.0
4            5         0  35.0

#### B-2 dataframe 기초함수

In [0]:
# 열 하나 추출
dft['Age'] # dft.Age

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [0]:
# 열 여러개 추출
dft[['Age', 'Survived']]

Age  Survived
0  22.0         0
1  38.0         1
2  26.0         1
3  35.0         1
4  35.0         0
5   NaN         0
6  54.0         0
7   2.0         0
8  27.0         1
9  14.0         1

In [0]:
# 행 하나 추출
dft.loc[5]

PassengerId    6.0
Survived       0.0
Age            NaN
Name: 5, dtype: float64

In [0]:
# 원하는 행의 원하는 열
dft.loc[7, 'Age']

2.0

In [0]:
# 여러 행의 여러 열 뽑기
dft.loc[[4,5,6],['Survived', 'Age']]

Survived   Age
4         0  35.0
5         0   NaN
6         0  54.0

In [0]:
# Filtering 기초
dft.Survived == 1

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7    False
8     True
9     True
Name: Survived, dtype: bool

In [0]:
dft[dft.Survived == 1] # dft[lambda x : x.Survived == 1]

PassengerId  Survived   Age
1            2         1  38.0
2            3         1  26.0
3            4         1  35.0
8            9         1  27.0
9           10         1  14.0

In [0]:
# A이거나 B일 조건
dft[lambda x : x.Age.isin([22,26,35])]

PassengerId  Survived   Age
0            1         0  22.0
2            3         1  26.0
3            4         1  35.0
4            5         0  35.0

In [0]:
# nan 값 개수 확인
df.isnull().sum() # df2.isnull().sum()/len(df2) -> nan의 비율 알 수 있음

PassengerId    0  
Survived       0  
Pclass         0  
Name           0  
Sex            0  
Age            177
SibSp          0  
Parch          0  
Ticket         0  
Fare           0  
Cabin          687
Embarked       2  
dtype: int64

In [0]:
# nan 값 삭제하기
# df_nonan = df[df.notnull().all(axis=1)] 도 같은 코드
df_nonan = df.dropna()
df_nonan.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [0]:
# 해당 column의 value 개수 확인
df['Embarked'].value_counts()

S    644
C    168
Q    77 
Name: Embarked, dtype: int64

In [0]:
# value 갯수의 크기별로 나열 (True -> 작은 것부터 / False -> 큰 것부터)
a = df['Embarked'].value_counts()
a = a.sort_values(ascending = True)
a

Q    77 
C    168
S    644
Name: Embarked, dtype: int64

In [0]:
# 위를 Dataframe으로 만들어주기
a = pd.DataFrame(a)
a

Embarked
Q  77      
C  168     
S  644

In [0]:
# 특정 column 중심으로 순서 정렬
df.sort_values('Name', ascending=True)

PassengerId  Survived  Pclass                                                                                Name     Sex    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
845  846          0         3       Abbing, Mr. Anthony                                                                 male    42.00  0      0      C.A. 5547           7.5500    NaN              S      
746  747          0         3       Abbott, Mr. Rossmore Edward                                                         male    16.00  1      1      C.A. 2673           20.2500   NaN              S      
279  280          1         3       Abbott, Mrs. Stanton (Rosa Hunt)                                                    female  35.00  1      1      C.A. 2673           20.2500   NaN              S      
308  309          0         2       Abelson, Mr. Samuel                                                                 male    30.00  1      0      P/PP 3381           24.0000   NaN              C      
874  875          1         2       Abelson, Mrs. Samuel (Hannah Wizosky)                                               female  28.00  1      0      P/PP 3381           24.0000   NaN              C      
365  366          0         3       Adahl, Mr. Mauritz Nils Martin                                                      male    30.00  0      0      C 7076              7.2500    NaN              S      
401  402          0         3       Adams, Mr. John                                                                     male    26.00  0      0      341826              8.0500    NaN              S      
40   41           0         3       Ahlin, Mrs. Johan (Johanna Persdotter Larsson)                                      female  40.00  1      0      7546                9.4750    NaN              S      
855  856          1         3       Aks, Mrs. Sam (Leah Rosen)                                                          female  18.00  0      1      392091              9.3500    NaN              S      
207  208          1         3       Albimona, Mr. Nassef Cassem                                                         male    26.00  0      0      2699                18.7875   NaN              C      
810  811          0         3       Alexander, Mr. William                                                              male    26.00  0      0      3474                7.8875    NaN              S      
840  841          0         3       Alhomaki, Mr. Ilmari Rudolf                                                         male    20.00  0      0      SOTON/O2 3101287    7.9250    NaN              S      
210  211          0         3       Ali, Mr. Ahmed                                                                      male    24.00  0      0      SOTON/O.Q. 3101311  7.0500    NaN              S      
784  785          0         3       Ali, Mr. William                                                                    male    25.00  0      0      SOTON/O.Q. 3101312  7.0500    NaN              S      
730  731          1         1       Allen, Miss. Elisabeth Walton                                                       female  29.00  0      0      24160               211.3375  B5               S      
4    5            0         3       Allen, Mr. William Henry                                                            male    35.00  0      0      373450              8.0500    NaN              S      
305  306          1         1       Allison, Master. Hudson Trevor                                                      male    0.92   1      2      113781              151.5500  C22 C26          S      
297  298          0         1       Allison, Miss. Helen Loraine                                                        female  2.00   1      2      113781              151.5500  C22 C26          S      
498  499          0         1       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)                                     female  2

In [0]:
# filtering (boolean indexing 반환)
df['Age'] > 30

0      False
1      True 
2      False
3      True 
4      True 
5      False
6      True 
7      False
8      False
9      False
10     False
11     True 
12     False
13     True 
14     False
15     True 
16     False
17     False
18     True 
19     False
20     True 
21     True 
22     False
23     False
24     False
25     True 
26     False
27     False
28     False
29     False
30     True 
31     False
32     False
33     True 
34     False
35     True 
36     False
37     False
38     False
39     False
40     True 
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     True 
53     False
54     True 
55     False
56     False
57     False
58     False
59     False
60     False
61     True 
62     True 
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     True 
71     False
72     False
73     False
74     True 
75     False
76     False

In [0]:
# 위를 DataFrame처럼 만들기 (조건에 해당하는 값만 나옴)
df[df['Age'] > 30].head()

PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
1   2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599  71.2833  C85   C      
3   4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803    53.1000  C123  S      
4   5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450    8.0500   NaN   S      
6   7            0         1       McCarthy, Mr. Timothy J                              male    54.0  0      0      17463     51.8625  E46   S      
11  12           1         1       Bonnell, Miss. Elizabeth                             female  58.0  0      0      113783    26.5500  C103  S

In [0]:
# 실수 경계선(카테고리) 나누기
df['AgeClass'] = pd.cut(df['Age'], bins=np.arange(0,90,10))
df.head()

PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  AgeClass
0  1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S        (20, 30]
1  2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C        (30, 40]
2  3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S        (20, 30]
3  4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S        (30, 40]
4  5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S        (30, 40]

In [0]:
# Age가 몇십대인지 계산 (위와 비슷)
df['AgeClass_s'] = df['Age']//10 * 10
print(df.columns)
df.head()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'AgeClass', 'AgeClass_s'], dtype='object')


PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  AgeClass  AgeClass_s
0  1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S        (20, 30]  20.0      
1  2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C        (30, 40]  30.0      
2  3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S        (20, 30]  20.0      
3  4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S        (30, 40]  30.0      
4  5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S        (30, 40]  30.0

In [0]:
# columns 지우기 (del, drop)
# 01 del
del df['AgeClass_s']
print(df.columns)
df.head()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'AgeClass'], dtype='object')


PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  AgeClass
0  1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S        (20, 30]
1  2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C        (30, 40]
2  3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S        (20, 30]
3  4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S        (30, 40]
4  5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S        (30, 40]

In [0]:
# 02 drop
df = df.drop(columns = 'AgeClass')
print(df.columns)
df.head()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], dtype='object')


PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S      
1  2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C      
2  3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S      
3  4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S      
4  5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S

In [0]:
# index 다시 설정
df.reset_index(inplace=True)
df.head()

index  PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  0      1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S      
1  1      2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C      
2  2      3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S      
3  3      4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S      
4  4      5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S

In [0]:
del df['index']
df.head()

PassengerId  Survived  Pclass                                                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   NaN   S      
1  2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C85   C      
2  3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   NaN   S      
3  4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  C123  S      
4  5            0         3       Allen, Mr. William Henry                             male    35.0  0      0      373450            8.0500   NaN   S

##### + 간단한 통계값
+ df['col'].mean() : 평균
+ df['col'].median() : 중앙값
+ df['col'].std() : 표준편차
+ df['col'].count() : 총 갯수
+ df['col'].sum() : 총합

In [0]:
# 반올림 round(반올림 값, 몇자리수까지)
round(df['Age'].std(),3)

14.526

#### B-3 create
칼럼 생성후, 데이터 추가하기

In [0]:
# 칼럼 생성
dfcc = pd.DataFrame(columns=['Age', 'Name'])
dfcc

Empty DataFrame
Columns: [Age, Name]
Index: []

In [0]:
# 칼럼에 테이터 넣기
dfcc['Age'] = [22,23]
dfcc['Name'] = ['Isa', 'Bella']
dfcc

Age   Name
0  22   Isa  
1  23   Bella

In [0]:
# Dictionary로 dataframe 생성
country = ['USA', 'ROK']
city = ['NYC', 'Seoul']
dic_Data = {'Country':country, 'City':city}
df_dic = pd.DataFrame(dic_Data) ;df_dic

Country   City
0     USA    NYC
1     ROK  Seoul

In [0]:
# index 수정
in_list = ['A', 'B']
dfc = pd.DataFrame(dic_Data, index=in_list) ;dfc

Country   City
A     USA    NYC
B     ROK  Seoul

In [0]:
# column을 index에 넣기
dfc.set_index('Country')

City
Country       
USA        NYC
ROK      Seoul

##### + random한 dataframe 생성

In [0]:
import random, string

In [0]:
# 랜덤한 이름 출력
def get_name():
    names = ['Cielo', 'Azul', 'Bella', 'Amor', 'vola']
    return random.choice(names)

get_name()

'Amor'

In [0]:
# 랜덤한 나이 출력
def get_age(start=10, end=30):
    return np.random.randint(start, end)

get_age()

19

In [0]:
# 랜덤한 성적 출력
def get_grade():
    grade = ['A','B','C','D', 'F']
    return random.choice(grade)

get_grade()

'B'

In [0]:
def make_data(rows=10):
    datas = []
    for i in range(rows):
        data = {'Name':get_name(), 'Age':get_age(), 'Grade':get_grade()}
        datas.append(data)
    return datas

make_data()

[{'Name': 'vola', 'Age': 22, 'Grade': 'A'},
 {'Name': 'Cielo', 'Age': 13, 'Grade': 'A'},
 {'Name': 'Bella', 'Age': 16, 'Grade': 'C'},
 {'Name': 'vola', 'Age': 21, 'Grade': 'B'},
 {'Name': 'Azul', 'Age': 21, 'Grade': 'D'},
 {'Name': 'Azul', 'Age': 10, 'Grade': 'B'},
 {'Name': 'Cielo', 'Age': 16, 'Grade': 'B'},
 {'Name': 'vola', 'Age': 25, 'Grade': 'F'},
 {'Name': 'Azul', 'Age': 20, 'Grade': 'B'},
 {'Name': 'Bella', 'Age': 12, 'Grade': 'B'}]

In [0]:
d1 = make_data()
df_md = pd.DataFrame(d1) ;df_md

Age Grade   Name
0  12   C     Amor 
1  11   F     Azul 
2  24   A     Bella
3  27   C     Cielo
4  25   C     Bella
5  28   D     vola 
6  10   F     Cielo
7  20   C     vola 
8  21   D     Cielo
9  26   F     Azul

##### + Append 함수
데이터 프레임을 합치고 싶을 때 사용

In [0]:
d2 = make_data()
df_md2 = pd.DataFrame(d2) ;df_md2

Age Grade   Name
0  25   A     Cielo
1  15   B     Bella
2  11   B     vola 
3  29   C     Cielo
4  14   F     Amor 
5  17   A     Amor 
6  12   A     Cielo
7  18   F     Amor 
8  12   D     Bella
9  22   C     Cielo

In [0]:
# 아래로 그대로 합쳐지는 형태
df_md3 = df_md.append(df_md2) ;df_md3

Age Grade   Name
0  12   C     Amor 
1  11   F     Azul 
2  24   A     Bella
3  27   C     Cielo
4  25   C     Bella
5  28   D     vola 
6  10   F     Cielo
7  20   C     vola 
8  21   D     Cielo
9  26   F     Azul 
0  25   A     Cielo
1  15   B     Bella
2  11   B     vola 
3  29   C     Cielo
4  14   F     Amor 
5  17   A     Amor 
6  12   A     Cielo
7  18   F     Amor 
8  12   D     Bella
9  22   C     Cielo

In [0]:
# index 리셋하기
# drop(True) : 새롭게 생성되는 인덱스 컬럼을 삭제
# inplace(True) : 함수를 사용하는 객체 자체 인덱스를 리셋
df_md3.reset_index(drop=True, inplace=True)
df_md3

Age Grade   Name
0   12   C     Amor 
1   11   F     Azul 
2   24   A     Bella
3   27   C     Cielo
4   25   C     Bella
5   28   D     vola 
6   10   F     Cielo
7   20   C     vola 
8   21   D     Cielo
9   26   F     Azul 
10  25   A     Cielo
11  15   B     Bella
12  11   B     vola 
13  29   C     Cielo
14  14   F     Amor 
15  17   A     Amor 
16  12   A     Cielo
17  18   F     Amor 
18  12   D     Bella
19  22   C     Cielo

#### B-4 Insert

In [0]:
# column 추가 (원본데이터 바뀜)
dfc['Weather'] = ['sunny', 'rain']
dfc

Country   City Weather
A     USA    NYC   sunny
B     ROK  Seoul    rain

In [0]:
# column 추가 (원본데이터 바뀌지 않음)
dfc.assign(Tomorrow_Weather = lambda x: x.Weather)

Country   City Weather Tomorrow_Weather
A     USA    NYC   sunny            sunny
B     ROK  Seoul    rain             rain

In [0]:
# row 추가 (맨 마지막 row에 추가)
dfc.loc[len(dfc)] = {'Country':"Canada", 'City':'Toronto', 'Weather':'cloudy'}
dfc

Country     City Weather
A  USA     NYC      sunny 
B  ROK     Seoul    rain  
2  Canada  Toronto  cloudy

##### + Apply 함수
함수를 이용하여 함수의 리턴값으로 Series를 만든 후 새로운 컬럼 생성

In [0]:
def score(row):
    return row * 4

dfcc['Score'] = dfcc['Age'].apply(score) ;dfcc

Age   Name  Score
0  22   Isa    88   
1  23   Bella  92

In [0]:
# lambda 나타낼 때 ',' 안쓰는 것 주의하기
dfcc['Pass'] = dfcc["Score"].apply(lambda x:'Y' if x > 90 else 'N')
dfcc

Age   Name  Score Pass
0  22   Isa    88     N  
1  23   Bella  92     Y

#### B-5 Groupby
기준이 되는 key를 통해 데이터를 분류 <br>
df.groupby(key)[column].operation() <br>
<br>
1. 같은 key를 지닌 데이터끼리 제시된 column값 모으기 <br>
2. operation 수행 <br>
01 size <br>
02 sort_value (groupby없이 위에서처럼 do) <br>
03 (aggregate) min, max, mean, sum, median

In [0]:
# size (reset_index() 해야 dataframe 형태로 나옴)
df = pd.read_csv('code_bella_data/titanic.csv')
df_s = df.groupby('Pclass').size().reset_index(name="Counts")
df_s

Pclass  Counts
0  1       216   
1  2       184   
2  3       491

In [0]:
# aggregate ([]가 한번이면 dataframe형식이 아님)
df.groupby('Sex')[['Survived']].aggregate(lambda x: x.sum())

Survived
Sex             
female  233     
male    109

In [0]:
df.groupby('Pclass')['Survived'].agg('sum').reset_index()

Pclass  Survived
0  1       136     
1  2       87      
2  3       119

In [0]:
# agg로 칼럼 여러개 생성
df_cl = df.groupby('Survived')[['Age']].agg(['mean', 'median', 'max', 'min'])
df_cl

Age                   
               mean median   max   min
Survived                              
0         30.626179  28.0   74.0  1.00
1         28.343690  28.0   80.0  0.42

In [0]:
# 여러개의 key로 groupby하기 (multi-index)
df_tk = df.groupby(['Survived','Sex']).size()
df_tk

Survived  Sex   
0         female    81 
          male      468
1         female    233
          male      109
dtype: int64

In [0]:
# two-key일 때는 [[ ]] or reset_index()가 아닌, unstack() 사용
df_tk.unstack()

Sex       female  male
Survived              
0         81      468 
1         233     109

In [0]:
# stack()은 반대 역할
a = df_tk.unstack()
a.stack()

Survived  Sex   
0         female    81 
          male      468
1         female    233
          male      109
dtype: int64

##### + loc와 iloc
loc : label에 따라 선택 <br>
iloc : 위치에 따라 선택

In [0]:
# loc[index, 찾고싶은 값의 column이름]
df_name = df.set_index('Name')
df_name.loc['Heikkinen, Miss. Laina','Fare']

7.925

In [0]:
# loc[이 index에서 : 이 index까지, :(=전체)]
df_name.loc['Heikkinen, Miss. Laina':'Allen, Mr. William Henry',:]

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch            Ticket    Fare Cabin Embarked
Name                                                                                                                                            
Heikkinen, Miss. Laina                        3            1         3       female  26.0  0      0      STON/O2. 3101282  7.925   NaN   S      
Futrelle, Mrs. Jacques Heath (Lily May Peel)  4            1         1       female  35.0  1      0      113803            53.100  C123  S      
Allen, Mr. William Henry                      5            0         3       male    35.0  0      0      373450            8.050   NaN   S

In [0]:
# iloc[index범위, column의 범위]
df.iloc[0:4,2:6]

Pclass                                                 Name     Sex   Age
0  3       Braund, Mr. Owen Harris                              male    22.0
1  1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0
2  3       Heikkinen, Miss. Laina                               female  26.0
3  1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0

##### + isin 함수
특정한 value의 위치를 찾고 싶을 때 사용

In [0]:
# df[해당 column에서].isin([이러한 value들 보고싶다])
df[df['Name'].isin(['Braund, Mr. Owen Harris','Heikkinen, Miss. Laina'])]

PassengerId  Survived  Pclass                     Name     Sex   Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0  1            0         3       Braund, Mr. Owen Harris  male    22.0  1      0      A/5 21171         7.250  NaN   S      
2  3            1         3       Heikkinen, Miss. Laina   female  26.0  0      0      STON/O2. 3101282  7.925  NaN   S

##### + startswith & str & contains

In [0]:
# df[해당 column에서].str.startswith('이걸로 시작하는 value 보고싶다')
df[df['Name'].str.startswith('A')].head()

PassengerId  Survived  Pclass                                                       Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
4   5            0         3       Allen, Mr. William Henry                                   male    35.0  0      0      373450  8.0500   NaN   S      
13  14           0         3       Andersson, Mr. Anders Johan                                male    39.0  1      5      347082  31.2750  NaN   S      
25  26           1         3       Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.0  1      5      347077  31.3875  NaN   S      
40  41           0         3       Ahlin, Mrs. Johan (Johanna Persdotter Larsson)             female  40.0  1      0      7546    9.4750   NaN   S      
49  50           0         3       Arnold-Franchi, Mrs. Josef (Josefine Franchi)              female  18.0  1      0      349237  17.8000  NaN   S

In [0]:
# 앞의 10자리까지만 보고 싶을 때 (위와 달리 앞뒤로 df[] 못붙임)
df['Name'].str[:10] # name이 짤려보임

0      Braund, Mr
1      Cumings, M
2      Heikkinen,
3      Futrelle, 
4      Allen, Mr.
5      Moran, Mr.
6      McCarthy, 
7      Palsson, M
8      Johnson, M
9      Nasser, Mr
10     Sandstrom,
11     Bonnell, M
12     Saundercoc
13     Andersson,
14     Vestrom, M
15     Hewlett, M
16     Rice, Mast
17     Williams, 
18     Vander Pla
19     Masselmani
20     Fynney, Mr
21     Beesley, M
22     McGowan, M
23     Sloper, Mr
24     Palsson, M
25     Asplund, M
26     Emir, Mr. 
27     Fortune, M
28     O'Dwyer, M
29     Todoroff, 
30     Uruchurtu,
31     Spencer, M
32     Glynn, Mis
33     Wheadon, M
34     Meyer, Mr.
35     Holverson,
36     Mamee, Mr.
37     Cann, Mr. 
38     Vander Pla
39     Nicola-Yar
40     Ahlin, Mrs
41     Turpin, Mr
42     Kraeff, Mr
43     Laroche, M
44     Devaney, M
45     Rogers, Mr
46     Lennon, Mr
47     O'Driscoll
48     Samaan, Mr
49     Arnold-Fra
50     Panula, Ma
51     Nosworthy,
52     Harper, Mr
53     Faunthorpe
54     Ostby, Mr.
55     Woo

In [0]:
# 길이가 15보다 작은 이름만 찾고 싶을 때
df[df['Name'].str.len() < 15].head()

PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch              Ticket     Fare Cabin Embarked
74   75           1         3       Bing, Mr. Lee   male  32.0  0      0      1601                56.4958  NaN   S      
169  170          0         3       Ling, Mr. Lee   male  28.0  0      0      1601                56.4958  NaN   S      
210  211          0         3       Ali, Mr. Ahmed  male  24.0  0      0      SOTON/O.Q. 3101311  7.0500   NaN   S      
509  510          1         3       Lang, Mr. Fang  male  26.0  0      0      1601                56.4958  NaN   S      
692  693          1         3       Lam, Mr. Ali    male NaN    0      0      1601                56.4958  NaN   S

In [0]:
# 특정한 것을 포함하는 행들을 찾고 싶을 때 contains 함수 사용
df[df['Name'].str.contains('al')].head()

PassengerId  Survived  Pclass                            Name     Sex  Age  SibSp  Parch  Ticket     Fare Cabin Embarked
7   8            0         3       Palsson, Master. Gosta Leonard  male    2.0  3      1      349909  21.0750  NaN   S      
24  25           0         3       Palsson, Miss. Torborg Danira   female  8.0  3      1      349909  21.0750  NaN   S      
29  30           0         3       Todoroff, Mr. Lalio             male   NaN   0      0      349216  7.8958   NaN   S      
63  64           0         3       Skoog, Master. Harald           male    4.0  3      2      347088  27.9000  NaN   S      
77  78           0         3       Moutal, Mr. Rahamin Haim        male   NaN   0      0      374746  8.0500   NaN   S

#### B-6 Data reshaping

In [0]:
ex = pd.DataFrame({'Month': ["January", "January", "January", "January", 
                                  "February", "February", "February", "February", 
                                  "March", "March", "March", "March"],
                   'Category': ["Transportation", "Grocery", "Household", "Entertainment",
                                "Transportation", "Grocery", "Household", "Entertainment",
                                "Transportation", "Grocery", "Household", "Entertainment"],
          'Amount': [74., 235., 175., 100., 115., 240., 225., 125., 90., 260., 200., 120.]})
ex

Month        Category  Amount
0   January   Transportation  74.0  
1   January   Grocery         235.0 
2   January   Household       175.0 
3   January   Entertainment   100.0 
4   February  Transportation  115.0 
5   February  Grocery         240.0 
6   February  Household       225.0 
7   February  Entertainment   125.0 
8   March     Transportation  90.0  
9   March     Grocery         260.0 
10  March     Household       200.0 
11  March     Entertainment   120.0

In [0]:
# pivot 함수
ex_pi = ex.pivot(index='Category', columns='Month', values='Amount')
ex_pi

Month           February  January  March
Category                                
Entertainment   125.0     100.0    120.0
Grocery         240.0     235.0    260.0
Household       225.0     175.0    200.0
Transportation  115.0     74.0     90.0

In [0]:
# 합구하기 (axis=0 이면 세로, axis=1 이면 가로)
ex_pi.sum(axis=1)

Category
Entertainment     345.0
Grocery           735.0
Household         600.0
Transportation    279.0
dtype: float64

##### + stack & unstack

In [0]:
ex_st = pd.DataFrame(ex.stack()) ; ex_st.head(6)

0
0 Month     January       
  Category  Transportation
  Amount    74            
1 Month     January       
  Category  Grocery       
  Amount    235

In [0]:
ex_ust = ex_st.unstack() ;ex_ust

0                       
       Month        Category Amount
0   January   Transportation  74   
1   January   Grocery         235  
2   January   Household       175  
3   January   Entertainment   100  
4   February  Transportation  115  
5   February  Grocery         240  
6   February  Household       225  
7   February  Entertainment   125  
8   March     Transportation  90   
9   March     Grocery         260  
10  March     Household       200  
11  March     Entertainment   120

##### + concat & merge

In [0]:
df_10 = pd.DataFrame({'A':['A0','A1','A2'],
                    'B':['B0','B1','B2'],
                    'C':['C0','C1','C2']})
df_20 = pd.DataFrame({'A':['A3','A4','A5'],
                    'E':['E3','E4','E5'],
                    'F':['F3','F4','F5']})
print(df_10, '\n'*2, df_20)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2 

     A   E   F
0  A3  E3  F3
1  A4  E4  F4
2  A5  E5  F5


In [0]:
# pd.concat([합치고 싶은 df])
# reset_index쓰면 index가 재편됨
# axis=0 : 위 아래, axis=1 : 왼쪽 오른쪽
pd.concat([df_10, df_20], axis = 0).reset_index(drop=True) 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  after removing the cwd from sys.path.


A    B    C    E    F
0  A0  B0   C0   NaN  NaN
1  A1  B1   C1   NaN  NaN
2  A2  B2   C2   NaN  NaN
3  A3  NaN  NaN  E3   F3 
4  A4  NaN  NaN  E4   F4 
5  A5  NaN  NaN  E5   F5

In [0]:
pd.concat([df_10, df_20], axis=1)

A   B   C   A   E   F
0  A0  B0  C0  A3  E3  F3
1  A1  B1  C1  A4  E4  F4
2  A2  B2  C2  A5  E5  F5

In [0]:
# join 추가하기 (outer : 합집합, inner : 교집합)
# 위에서처럼 join 안쓰면 자동 outer처럼 됨
pd.concat([df_10, df_20], axis = 0, join = 'outer')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  This is separate from the ipykernel package so we can avoid doing imports until


A    B    C    E    F
0  A0  B0   C0   NaN  NaN
1  A1  B1   C1   NaN  NaN
2  A2  B2   C2   NaN  NaN
0  A3  NaN  NaN  E3   F3 
1  A4  NaN  NaN  E4   F4 
2  A5  NaN  NaN  E5   F5

In [0]:
pd.concat([df_10, df_20], axis = 0, join = 'inner').reset_index(drop=True)

A
0  A0
1  A1
2  A2
3  A3
4  A4
5  A5

In [0]:
df_11 = pd.DataFrame({
    'ID' : [1,2,3,4,5],
    'Name' : ['Bella','Tina','Irene','Jane','Seine']
    })
df_21 = pd.DataFrame({
    'ID' : [1,3,5,7],
    'Age' : ['22','15','26','19']
    })
print(df_11,'\n'*2,df_21)

   ID   Name
0  1   Bella
1  2   Tina 
2  3   Irene
3  4   Jane 
4  5   Seine 

    ID Age
0  1   22
1  3   15
2  5   26
3  7   19


In [0]:
# merge로 합해주기_ 2가지 방식(여기서 default는 inner join)
print(pd.merge(df_11, df_21))
df_11.merge(df_21)

   ID   Name Age
0  1   Bella  22
1  3   Irene  15
2  5   Seine  26


ID   Name Age
0  1   Bella  22
1  3   Irene  15
2  5   Seine  26

In [0]:
# 01 inner join (교집합) _여기선 위와 같은 결과
pd.merge(df_11, df_21, how='inner', on='ID')

ID   Name Age
0  1   Bella  22
1  3   Irene  15
2  5   Seine  26

In [0]:
# 02 left join (왼쪽에 존재하는 데이터 기준)
pd.merge(df_11, df_21, how='left', on='ID')

ID   Name  Age
0  1   Bella  22 
1  2   Tina   NaN
2  3   Irene  15 
3  4   Jane   NaN
4  5   Seine  26

In [0]:
# 03 right join (오른쪽에 존재하는 데이터 기준)
pd.merge(df_11, df_21, how='right', on='ID')

ID   Name Age
0  1   Bella  22
1  3   Irene  15
2  5   Seine  26
3  7   NaN    19

In [0]:
# 04 full join (합집합)
pd.merge(df_11, df_21, how='outer', on='ID')

ID   Name  Age
0  1   Bella  22 
1  2   Tina   NaN
2  3   Irene  15 
3  4   Jane   NaN
4  5   Seine  26 
5  7   NaN    19

#### B-7 timeseries data

In [0]:
import datetime

In [0]:
# 시간 임의로 지정 (datetime.datetime())
dt = datetime.datetime(year = 2020, month = 6, day = 2, hour = 4, minute = 31)
print(dt)

2020-06-02 04:31:00


In [0]:
# dt.strftime()
print(dt.strftime('%d %B %Y'))

02 June 2020


In [0]:
# pd.Timestamp
ts = pd.Timestamp('2020-06-02')
print(ts, '\n'*2, 'month :',ts.month)

2020-06-02 00:00:00 

 month : 6


In [0]:
# pd.Timedelta()
ts + pd.Timedelta('5 days')

Timestamp('2020-06-07 00:00:00')

In [0]:
# pd.to_datetime()
#pd.to_datetime('2020-02-09')
pd.to_datetime('06/02/2020') # 2개 동일함

Timestamp('2020-06-02 00:00:00')

In [0]:
# dayfirst = True 이면 월, 일 change
pd.to_datetime('06/02/2020', dayfirst = True)

Timestamp('2020-02-06 00:00:00')

In [0]:
# 직접 순서를 정해주고 싶은 경우
pd.to_datetime('2020/06/02', format = '%Y/%m/%d')

Timestamp('2020-06-02 00:00:00')

In [0]:
s = pd.Series(['2020-06-01 10:00:00', '2020-06-02, 11:00:00', '2020-06-03 12:00:00'])
ts = pd.to_datetime(s)
ts

0   2020-06-01 10:00:00
1   2020-06-02 11:00:00
2   2020-06-03 12:00:00
dtype: datetime64[ns]

In [0]:
# 특정한 value만 보기 (일요일=0)
print(ts.dt.hour, '\n'*2, ts.dt.weekday)

0    10
1    11
2    12
dtype: int64 

 0    0
1    1
2    2
dtype: int64


In [0]:
# 특정한 규칙으로 시간대를 생성하고 싶을 때
# 6월 2일부터 5번 7일씩
pd.Series(pd.date_range(start = '2020-06-02',periods = 5,freq='7d'))

0   2020-06-02
1   2020-06-09
2   2020-06-16
3   2020-06-23
4   2020-06-30
dtype: datetime64[ns]

In [0]:
data = pd.read_csv('code_bella_data/flowdata.csv')
data.head()

Time   L06_347  LS06_347  LS06_348
0  2009-01-01 00:00:00  0.137417  0.097500  0.016833
1  2009-01-01 03:00:00  0.131250  0.088833  0.016417
2  2009-01-01 06:00:00  0.113500  0.091250  0.016750
3  2009-01-01 09:00:00  0.135750  0.091500  0.016250
4  2009-01-01 12:00:00  0.140917  0.096167  0.017000

In [0]:
# index를 time으로 설정하기
data = data.set_index("Time")
data.head()

L06_347  LS06_347  LS06_348
Time                                             
2009-01-01 00:00:00  0.137417  0.097500  0.016833
2009-01-01 03:00:00  0.131250  0.088833  0.016417
2009-01-01 06:00:00  0.113500  0.091250  0.016750
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-01 12:00:00  0.140917  0.096167  0.017000

In [0]:
# 애초에 Time을 index로 가져오기
data = pd.read_csv('code_bella_data/flowdata.csv',index_col = 0, parse_dates = True)
data.head()

L06_347  LS06_347  LS06_348
Time                                             
2009-01-01 00:00:00  0.137417  0.097500  0.016833
2009-01-01 03:00:00  0.131250  0.088833  0.016417
2009-01-01 06:00:00  0.113500  0.091250  0.016750
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-01 12:00:00  0.140917  0.096167  0.017000

In [0]:
# index에서 월,일 등 확인하기
data.index.day

Int64Index([ 1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
            ...
            31,  1,  1,  1,  1,  1,  1,  1,  1,  2], dtype='int64', name='Time', length=11697)

##### + data slicing

In [0]:
# 원하는 시간대 가져오기
#data[pd.Timestamp("2012-01-01 09:00"):pd.Timestamp("2012-01-01 19:00")]
data['2012-01-01 09:00':'2012-01-01 19:00'] # 2개는 서로 같음

L06_347  LS06_347  LS06_348
Time                                             
2012-01-01 09:00:00  0.330750  0.293583  0.029750
2012-01-01 12:00:00  0.295000  0.285167  0.031750
2012-01-01 15:00:00  0.301417  0.287750  0.031417
2012-01-01 18:00:00  0.322083  0.304167  0.038083

In [0]:
data['2012-01':'2012-02'].head()

L06_347  LS06_347  LS06_348
Time                                             
2012-01-01 00:00:00  0.307167  0.273917  0.028000
2012-01-01 03:00:00  0.302917  0.270833  0.030583
2012-01-01 06:00:00  0.331500  0.284750  0.030917
2012-01-01 09:00:00  0.330750  0.293583  0.029750
2012-01-01 12:00:00  0.295000  0.285167  0.031750

##### + reshape 함수 사용

In [0]:
# 날을 기준으로 평균
data.resample('D').mean().head()

L06_347  LS06_347  LS06_348
Time                                    
2009-01-01  0.125010  0.092281  0.016635
2009-01-02  0.124146  0.095781  0.016406
2009-01-03  0.113562  0.085542  0.016094
2009-01-04  0.140198  0.102708  0.017323
2009-01-05  0.128812  0.104490  0.018167

In [0]:
# 달을 기준으로 표준편차
data.resample('m').std().head()

L06_347  LS06_347  LS06_348
Time                                    
2009-01-31  1.191254  1.265982  0.077004
2009-02-28  0.849708  0.928559  0.051784
2009-03-31  0.382025  0.476594  0.030594
2009-04-30  0.057338  0.056380  0.006530
2009-05-31  0.529870  0.573700  0.046361

In [0]:
# 년을 기준으로 max
data.resample('Y').max().head()

L06_347   LS06_347  LS06_348
Time                                      
2009-12-31  9.046667   9.353333   0.637500
2010-12-31  25.658333  25.658333  1.328333
2011-12-31  10.365000  10.251667  0.682833
2012-12-31  6.249167   6.079167   0.483583
2013-12-31  2.693333   2.693333   0.207333